# Generated by Django 3.0.3 on 2020-05-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_voters', models.IntegerField()),
                ('last_billed', models.DateField()),
                ('rate_per_voter', models.FloatField()),
                ('password', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=300)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('username', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('options', models.ManyToManyField(to='api.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('secret', models.CharField(max_length=8)),
                ('parent_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('time_placed', models.DateField()),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Voter')),
            ],
        ),
        migrations.CreateModel(
            name='TopicResults',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic')),
                ('votes', models.ManyToManyField(to='api.Vote')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
                ('topics', models.ManyToManyField(to='api.Topic')),
                ('voters', models.ManyToManyField(to='api.Voter')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('process_id', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
                ('topic_results', models.ManyToManyField(to='api.TopicResults')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='results',
            field=models.ManyToManyField(to='api.Results'),
        ),
        migrations.AddField(
            model_name='host',
            name='voters',
            field=models.ManyToManyField(to='api.Voter'),
        ),
        migrations.AddField(
            model_name='host',
            name='voting_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
        ),
    ]
