# Generated by Django 3.0.3 on 2020-05-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='last_billed',
        ),
        migrations.RemoveField(
            model_name='host',
            name='rate_per_voter',
        ),
    ]
