# Generated by Django 3.0.3 on 2020-05-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200505_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='voting_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
        ),
    ]
