# Generated by Django 3.0.3 on 2020-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='software_running',
            field=models.BooleanField(default=False),
        ),
    ]
