# Generated by Django 3.0.3 on 2020-05-17 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200517_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
