# Generated by Django 3.0.3 on 2020-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200517_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hide_voters',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
