# Generated by Django 3.0.3 on 2020-05-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_session_hide_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='parent_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Host'),
        ),
    ]
