# Generated by Django 3.0.3 on 2020-05-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200517_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
    ]
